### DISCUSSION TITLE
How to add DNSCrypt DoH to list of known servers on Windows 11

### DISCUSSION THREAD

**Discussion by poqdavid** [DNSCrypt/dnscrypt-proxy#2108] [Q&A]
I wanted to use the DNSCrypt DoH with Windows 11 and I am not 100% sure what is the proper way to do that

These are the commands I think might be possibly right
```
netsh dns add encryption server=127.0.0.100 dohtemplate=https://localhost.doh/dns-query autoupgrade=yes udpfallback=no
netsh dns add encryption server=127.0.0.200 dohtemplate=https://localhost.doh/dns-query autoupgrade=yes udpfallback=no

or 

Add-DnsClientDohServerAddress -ServerAddress '127.0.0.100' -DohTemplate 'https://localhost.doh/dns-query' -AllowFallbackToUdp $False -AutoUpgrade $True
Add-DnsClientDohServerAddress -ServerAddress '127.0.0.200' -DohTemplate 'https://localhost.doh/dns-query' -AllowFallbackToUdp $False -AutoUpgrade $True
```

And this is how I configured my Local DoH server
```toml
##################################
#        Local DoH server        #
##################################

[local_doh]

listen_addresses = ['127.0.0.100:443', '127.0.0.200:443']

path = "/dns-query"

cert_file = "..\\..\\ssl\\fullchain.crt"
cert_key_file = "..\\..\\ssl\\privkey.key"
```
Also my `captive-portals.txt` file

```
captive.apple.com               17.253.109.201, 17.253.113.202
connectivitycheck.gstatic.com   64.233.162.94, 64.233.164.94, 64.233.165.94, 64.233.177.94, 64.233.185.94, 74.125.132.94, 74.125.136.94, 74.125.20.94, 74.125.21.94, 74.125.28.94
connectivitycheck.android.com   64.233.162.100, 64.233.162.101, 64.233.162.102, 64.233.162.113, 64.233.162.138, 64.233.162.139
www.msftncsi.com                2.16.106.89, 2.16.106.91, 23.0.175.137, 23.0.175.146, 23.192.47.155, 23.192.47.203, 23.199.63.160, 23.199.63.184, 23.199.63.208, 23.204.146.160, 23.204.146.163, 23.46.238.243, 23.46.239.24, 23.48.39.16, 23.48.39.48, 23.55.38.139, 23.55.38.146, 23.59.190.185, 23.59.190.195
dns.msftncsi.com                131.107.255.255, fd3e:4f5a:5b81::1
www.msftconnecttest.com         13.107.4.52
ipv6.msftconnecttest.com        2a01:111:2003::52
ipv4only.arpa                   192.0.0.170, 192.0.0.171
localhost.doh                127.0.0.100, 127.0.0.200
```
Should both `autoupgrade` and `udpfallback` be set to yes/true?
