### DISCUSSION TITLE
Trying to set up dnscrypt with cloudflare gateway

### DISCUSSION THREAD

**Discussion by metasikander** [DNSCrypt/dnscrypt-proxy#2244] [Q&A] [answered]
So I'm trying to set up `dnscrypt-proxy` with my personal **Cloudflare Gateway**, but are having issues with the minisig pubkey.
Does anyone know if it's possible, and if so how to set it up?

According to someone in the cloudflare community it should be enough with just the DoH url: https://community.cloudflare.com/t/zero-trust-with-dnscrypt-proxy/436287

```toml
  [sources.'<name of my gateway>']
    urls = ['https://<my gateway id>.cloudflare-gateway.com/dns-query']
    cache_file = '/var/cache/dnscrypt-proxy/gateway.md'
    minisign_key = ''
    refresh_delay = 72
    prefix = ''
```

output from the service:
```
nov. 18 13:18:14 s2s-local dnscrypt-proxy[18452]: Source [relays] loaded
nov. 18 13:18:14 s2s-local dnscrypt-proxy[18452]: Missing Minisign key for source [<gateway>]
nov. 18 13:18:14 s2s-local systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/EXCEPTION
nov. 18 13:18:14 s2s-local systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
```
