### DISCUSSION TITLE
I didn't manage to start the program; it doesn't print anything and Ctrl-C doesn't quit

### DISCUSSION THREAD

**Discussion by valir777** [DNSCrypt/dnscrypt-proxy#2720] [Q&A]
hi guys so i recently downloaded the program and configured the file dnscrypt-proxy.toml,after starting the program doesn't show anything and doesn't stop with the command cntrl+c, in the dns settings i specified 127.0.0.0.1 but no sites are loaded with it, please tell me what i'm doing wrong?btw yes i use sudo -s to start
os:mac os 15.1
my .toml

```toml
server_names = ['dnscry.pt-amsterdam02-ipv4', 'dnscry.pt-nuremberg-ipv4', 'dnscry.pt-toronto-ipv4', 'dnscry.pt-dallas-ipv6']
listen_addresses = ['127.0.0.1:53', '[::1]:53']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
odoh_servers = false
force_tcp = false
http3 = false
timeout = 5000
keepalive = 30
log_level = 0
log_file = 'dnscrypt-proxy.log'
cert_refresh_delay = 240
dnscrypt_ephemeral_keys = true
tls_disable_session_tickets = true
bootstrap_resolvers = ['9.9.9.11:53', '8.8.8.8:53']
ignore_system_dns = true
netprobe_timeout = 30
netprobe_address = '9.9.9.9:53'
log_files_max_size = 1
log_files_max_age = 7
log_files_max_backups = 1
block_ipv6 = false
block_unqualified = true
block_undelegated = true
reject_ttl = 10
cache = true
cache_size = 1024
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
[sources]
[sources. 'relays']
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md']
cache_file = 'relays.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''
[anonymized_dns]
routes = [
{ server_name='dnscry.pt-amsterdam02-ipv4', via=['anon-cs-austria', 'anon-cs-barcelona'] },
{ server_name='dnscry.pt-nuremberg-ipv4', via=['anon-cs-belgium', 'anon-cs-berlin'] },
{ server_name='dnscry.pt-toronto-ipv4', via=['anon-cs-bulgaria', 'anon-cs-ch'] },
{ server_name='dnscry.pt-dallas-ipv6', via=['anon-cs-dk', 'anon-cs-finland'] },
]
skip_incompatible = true
```
logs:
[2024-10-30 20:57:04] [NOTICE] dnscrypt-proxy 2.1.5
[2024-10-30 20:57:04] [NOTICE] Network connectivity detected
[2024-10-30 20:57:04] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
[2024-10-30 20:57:04] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
[2024-10-30 20:57:04] [NOTICE] Now listening to [::1]:53 [UDP]
[2024-10-30 20:57:04] [NOTICE] Now listening to [::1]:53 [TCP]
[2024-10-30 20:57:04] [NOTICE] Source [relays] loaded
[2024-10-30 20:57:04] [FATAL] No servers configured
