### DISCUSSION TITLE
unsupported protocol scheme "file"

### DISCUSSION THREAD

**Discussion by LordGrimmauld** [DNSCrypt/dnscrypt-proxy#2775] [Potential issues]
I wanted to set a local file as a resolver url list.

For this, i set something like this:
```toml
[sources.public-resolvers]
cache_file = "/var/lib/dnscrypt-proxy2/public-resolvers.md"
minisign_key = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"
urls = ["file:///path/to/public-resolvers.md"]
```

An approach like this means i can pin my resolver list and administrate it using e.g. NixOS tooling. It also means i don't rely on the packaged bootstrap process.

The packaged bootstrap process failed, because my bios clock reset itself, thus any certificate was "from the future", while my time sync service could not sync time because it was lacking DNS. This issue is on me, but part of the motivation for "offline resolver URL lists".

However: Trying this, i quickly found out dnscrypt-proxy really does not appreciate this. It immediately crashed with `[FATAL] Get "file:///nix/store/drbdbm8zdgh3d2v447fxspzzpcmaqiwp-public-resolvers.md": unsupported protocol scheme "file"`.

Seeing as this failure mode is loud and obvious, and definitely something i made happen with my setup, this is opened as a discussion. However, i do believe my use case is valid and would love this resolved.

Filed as "potential issue" because this is somewhere between weird setup, feature request and just a real issue. Also for the record: Setting a remote resolver URL list works perfectly fine, and extremely well for my use cases too! Pairs nicely with the rest of my paranoid setup, thank you all for the good work.
