### ISSUE TITLE
IPv4/ipv6 Dual Stack

### ISSUE THREAD

**Issue by Gill-Bates** [DNSCrypt/dnscrypt-proxy#1061]
I am using Encrypted DNS Server and running the machine in dual stack mode.

I have generated a ipv4 and an ipv6 Stamp.

How can I merge both inside my [static] section inside my iOS DNS Cloak config file?

**Comment by jedisct1** [comment]
You can have as many static entries as you like. So, create one for IPv6, one for IPv4:

```toml
  [static.'my server over ipv4']
  stamp = 'sdns:AQcAAAAAAAAAAAAQMi5kbnNjcnlwdC1jZXJ0Lg'

  [static.'my server over ipv6']
  stamp = 'sdns:AQcAAAAAAAAAAAAQMi5kbnNjcnlwdC1jZXJ0Lg'
```
