### ISSUE TITLE
Anonymization not working for me

### ISSUE THREAD

**Issue by Shadow505** [DNSCrypt/dnscrypt-proxy#1346]
I am unable to get the anonymization feature (via relays) working. No matter what combination (resolver & relay) I try, they all fail with the following error message:

> [WARNING] [XYZ] is incompatible with anonymization

For example, I tried:

```
routes = [
    { server_name='ffmuc.net', via=['anon-meganerd', 'anon-cs-fr', 'anon-cs-fr2'] },
    { server_name='meganerd', via=['anon-kama', 'anon-cs-fr', 'anon-cs-fr2'] },
    { server_name='dnscrypt.uk-ipv4', via=['anon-dnscrypt.uk-ipv4'] },
    { server_name='dnscrypt.eu-nl', via=['anon-skyfighter'] }
]
```

I am using the latest release (2.0.42).

Thanks for your help!

**Comment by BraneStawm23** [comment]
Hi Shadow505.

I just had a look at my config and it appears to be set out differently to yours. I just checked the example config document and you have followed the format therein. I used SimpleDNSCrypt to set mine up and the anonymized route section looks like this:

```toml
[anonymized_dns]
skip_incompatible = false

[[anonymized_dns.routes]]
server_name = "ams-dnscrypt-nl"
via = ["anon-kama", "anon-dnscrypt.uk-ipv4"]
[[anonymized_dns.routes]]
server_name = "scaleway-fr"
via = ["anon-kama", "anon-scaleway"]
[[anonymized_dns.routes]]
server_name = "sth-dnscrypt-se"
via = ["anon-v.dnscrypt.uk-ipv4", "anon-scaleway-ams"]
```

ALSO: Check you have the Server_Names section at the top of the file, eg,
`server_names = ['ams-dnscrypt-nl', 'sth-dnscrypt-se', 'scaleway-fr']`

Maybe try reformatting and give it another try.
Hope this helps
