### ISSUE TITLE
block_unqualified = true # Thanks for this.. 

### ISSUE THREAD

**Issue by bcookatpcsd** [DNSCrypt/dnscrypt-proxy#1458]
https://arstechnica.com/gadgets/2020/08/a-chrome-feature-is-creating-enormous-load-on-global-root-dns-servers/

```toml
## Immediately respond to A and AAAA queries for host names without a domain name

block_unqualified = true

## Immediately respond to queries for local zones instead of leaking them to
## upstream resolvers (always causing errors or timeouts).

block_undelegated = true
```

Thanks for this.. 

My little 5k nodes on the Interweb don't contribute to this because of you..
