### ISSUE TITLE
Automatic relay route selection

### ISSUE THREAD

**Issue by guillaumerenault** [DNSCrypt/dnscrypt-proxy#1555]
## Is your feature request related to a problem?

Issue #1553 made me think that random relay selection would be a good option to have.
This might be a duplicate of issue #1385 

## Describe the solution you'd like

The relay selection would be done the same way as servers are chosen (probing for latency).
Relay routes for a server would be validated and tested at startup in accordance with the settings and then used for a specific amount of time before getting flushed and probed again
Ideally 6 configuration settings would be available:
```toml
automatic_relays = true # bool
min_number_of_relays = 3 # int (1-...)
max_number_of_relays = 5 # int(1-...)
min_rtt_between_first_relay_and_dnscrypt_resolver = 75 #  int (milliseconds, ...) (to ensure the first relay and the final dnscrypt-server are a bit far from each other)
max_total_rtt = 150 # int (milliseconds, ...) (total rtt between original client and final dnscrypt-server when using a relay route)
min_number_of_routes_per_server = 1 # int(1-...) min number of relay routes for a specific dnscrypt-server in order to use it
```

## Alternatives you've considered

Manually updating the configuration to create different routes of relays, for servers, this can be done via a script etc...

## Who will that feature be useful to?

Improving privacy and less manual configuration required to set and use relay routes

## What are you going to contribute?

I have no real experience with Go (apart from installing things) but I'm willing to try
Write documentation
