### ISSUE TITLE
show-certs returns empty output

### ISSUE THREAD

**Issue by ebal** [DNSCrypt/dnscrypt-proxy#1717]
## Please read before filling a bug report

This tracker is dedicated to tracking bugs, reproducible in the context described in the
"Context" section.

Installation and configuration issues are not bugs, but individual assistance request.
In order to ask for help, please use the discussions (Q&A) section instead:
https://github.com/DNSCrypt/dnscrypt-proxy/discussions/categories/q-a

Context: the LATEST version of `dnscrypt-proxy` (precompiled binaries downloaded from this
```sh
$ dnscrypt-proxy -version
2.0.45
```

```sh
$ dnscrypt-proxy -check

$ dnscrypt-proxy -show-certs

$ dnscrypt-proxy -list
myserver
```

```sh
$ dnscrypt-proxy -resolve example.com
Resolving [example.com] using 127.0.0.1 port 53

Resolver      : 172.68.61.180
Lying         : no
DNSSEC        : yes, the resolver supports DNSSEC

Canonical name: example.com.

IPv4 addresses: 93.184.216.34
IPv6 addresses: 2606:2800:220:1:248:1893:25c8:1946

Name servers  : a.iana-servers.net., b.iana-servers.net.
DNSSEC signed : yes
Mail servers  : 1 mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : -
TXT records   : v=spf1 -all, 8j5nfqld20zpcyr8xjw0ydcfq9rk8hgm
```

I am trying to create & verify dns stamps and wanted to use dnscrypt-proxy to verify chain as i understood from https://github.com/jedisct1/doh-server#operational-recommendations.

I am using dncrypt-proxy for quiet some time now, not a problem at all

my toml file (after editing to test static) 

```toml
##server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']
server_names = ['myserver']

[static]

  [static.'myserver']
  stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEAEmRucy5jbG91ZGZsYXJlLmNvbQovZG5zLXF1ZXJ5'
```

stamp tested from cloudflare
