### ISSUE TITLE
beta: server_name='*' in routes requires both DNSCrypt and ODoH relays

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#1739]
Routes can mix DNSCrypt and ODoH relays:

```toml
[anonymized_dns]
routes = [ { server_name='*', via=['odohrelay-crypto-sx', 'anon-kama'] } ]
```

In that case, each category picks their compatible relays as expected.

However:

```toml
[anonymized_dns]
routes = [ { server_name='*', via=['odohrelay-crypto-sx'] } ]
```

This causes DNSCrypt servers to be considered as having an empty relay set. We should act as if there was no relay defined instead.
