### ISSUE TITLE
[FATAL] Missing stamp

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#28]
`[FATAL] Missing stamp for the static [server-of-my-choice] definition`

Can't run `beta 9` without this error. No connection.

• `[sources]` settings doesn't matter - `[sources.'legacy resolvers list for dnscrypt-proxy v1']` or `[sources.'proxy v1 list from github']`
• Lines for the **server-of-my-choice** are equal in the in both `*.csv` files - from the **new** and from the **old** URLs.

**Comment by jedisct1** [comment]
You are probably using an old configuration file, which is not compatible with newer betas.

As the message says, stamps are required for static definitions, and your configuration may be missing one.

**Comment by iWARR** [comment]
I'm using this:

```
[servers]

  [servers.'server-of-my-choice']
  provider_name = '...'
  address = '...'
  public_key = '...'
```

**Comment by iWARR** [comment]
I'm sorry, but what the place I can find the corresponding value of `stamp =` parameter for the **server-of-my-choice** ?

**Comment by jedisct1** [comment]
```
provider_name = '...'
address = '...'
public_key = '...'
```

These don't exist any more, since they only work with DNSCrypt, and the goal is to eventually support more protocols.

If you are running your own server, `dnscrypt-wrapper` should have printed the stamp.

If you are using a public server, you don't need anything in that section. Just fill in a server name in `servers_name`.

**Comment by iWARR** [comment]
Don't work.
I'm using a public server and now leaving section [sources] as it is (except `cache_file = `)

• If I delete [servers] and all lines below :
`[FATAL] No servers configured`

• If I leave [servers] like this :
```
[servers]
  [servers.'server-of-my-choice']
```
I've got :
`[FATAL] Missing stamp for the static [server-of-my-choice] definition`

Seems like `stamp =` is the MUST value (for now)...

**Comment by jedisct1** [comment]
The proxy needs to know where to download server lists from.

The example configuration file has this section:

```toml
[sources]
  [sources.'legacy resolvers list for dnscrypt-proxy v1']
  url = 'https://download.dnscrypt.info/resolvers-list/v1/dnscrypt-resolvers.csv'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  cache_file = 'dnscrypt-resolvers.csv'
  format = 'v1'
  refresh_delay = 168
  prefix = ''
```

Do not remove it, this is needed.
