### ISSUE TITLE
Quad9 DOH!

### ISSUE THREAD

**Issue by D1n0Bot** [DNSCrypt/dnscrypt-proxy#612]
How do we use DOH for Quad9.
https://www.quad9.net/doh-quad9-dns-servers/
Where is the stamp? What do we put as hashes?

**Comment by r4sas** [comment]
You can generate it yourself here: https://dnscrypt.info/stamps

**Comment by jedisct1** [comment]
You don't need to do anything beside put their server names in `server_names`; their resolvers are in the default resolvers list: https://dnscrypt.info/public-servers

See all the resolvers whose name begins with "quad9".

**Comment by jedisct1** [comment]
They also publish a source of resolvers that you can add to your `dnscrypt.toml` file:

```toml
 [sources.quad9-resolvers]
 urls = ["https://www.quad9.net/quad9-resolvers.md"]
 minisign_key = "RWQBphd2+f6eiAqBsvDZEBXBGHQBJfeG6G+wJPPKxCZMoEQYpmoysKUN"
 cache_file = "quad9-resolvers.md"
 refresh_delay = 72
 prefix = "quad9-"
```
