### ISSUE TITLE
whitelist entry overwritten bei blacklist wildcard

### ISSUE THREAD

**Issue by scubasunny** [DNSCrypt/dnscrypt-proxy#613]
I have blocked some (porn) tubes by adding *tube* to the blacklist.
Unfortunately for me son this also blocks access to youtube ;-)
Therefore i added *youtube* to the whitelist.

But this does not work, youtube is still blocked (overwritten ?) by the more general blacklist pattern.

It this somehow by intention or just to treated properly?

**Comment by jedisct1** [comment]
The whitelist should have a higher priority than blacklists.

Can you post a minimal set of configuration files that reproduces this issue?

Blocking short general keywords such as `tube` is bound to block a lot of false positives, and not be very efficient against blocking porn. You'd rather use [cleanbrowsing](https://cleanbrowsing.org/) or [sfw.scaleway-fr](https://fr.dnscrypt.info/sfw.html).

And, of course, cloaking, but you probably already do :)

**Comment by scubasunny** [comment]
```toml
[blacklist]
blacklist_file = "C:\\Program Files\\bitbeans\\Simple DNSCrypt x64\\dnscrypt-proxy\\blacklist.txt"
log_file = "blocked.log"
log_format = "ltsv"

[whitelist]
whitelist_file = "C:\\Program Files\\bitbeans\\Simple DNSCrypt x64\\dnscrypt-proxy\\domain-whitelist.txt"
log_file = "C:\\Program Files\\bitbeans\\Simple DNSCrypt x64\\dnscrypt-proxy\\whitelisted.log"
log_format = "ltsv"
```
