### ISSUE TITLE
macOS - [FATAL] Unable to reexecute 

### ISSUE THREAD

**Issue by skull-squadron** [DNSCrypt/dnscrypt-proxy#618]
### Environment

- macOS 10.14 (SIP disabled, for other reasons)
- brew installed dnscrypt-proxy 2.0.17
- `/usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy` has permissions 555, owner $USER and group staff

### Invocation

`sudo /usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy -config /path/to/config.toml`

### Output

```
[2018-10-17 21:29:19] [NOTICE] Source [public-resolvers.md] loaded
[2018-10-17 21:29:19] [NOTICE] dnscrypt-proxy 2.0.17
[2018-10-17 21:29:19] [NOTICE] Dropping privileges
[2018-10-17 21:29:19] [FATAL] Unable to reexecute [/usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy]
```

### Output but rerunning with `sudo dtruss ...`

[See this gist](https://gist.github.com/steakknife/763e9b93c5a6663518135ef87facdf09)

### Config

```toml
# has permissions 644
server_names = ['cs-uswest3', 'cs-uswest4']
listen_addresses = ['127.0.0.1:5300', '[::1]:5300']
max_clients = 250
user_name = 'nobody'
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = false
require_nolog = true
require_nofilter = true
force_tcp = false
timeout = 2500
keepalive = 30
cert_refresh_delay = 240
fallback_resolver = '9.9.9.9:53'
ignore_system_dns = false
netprobe_timeout = 30
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
block_ipv6 = false
cache = true
cache_size = 512
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
[query_log]
  format = 'tsv'
[nx_log]
  format = 'tsv'
[blacklist]
[ip_blacklist]
[whitelist]
[schedules]
[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
[static]
```
